"""empty message

Revision ID: 3145f046c8d3
Revises: 
Create Date: 2024-01-05 14:33:57.459459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3145f046c8d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('lot_size', sa.Float(), nullable=False),
    sa.Column('square_footage', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings_table.id'], name=op.f('fk_favorite_table_listing_id_listings_table')),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_favorite_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings_table.id'], name=op.f('fk_image_table_listing_id_listings_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_table')
    op.drop_table('favorite_table')
    op.drop_table('users_table')
    op.drop_table('listings_table')
    # ### end Alembic commands ###
